services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/activecypher
    volumes:
      - neo4j_data:/data

  memgraph:
    image: memgraph/memgraph-mage:latest
    ports:
      - "7688:7687" # Bolt protocol
      - "7444:7444"
    environment:
      - MEMGRAPH_USER=memgraph
      - MEMGRAPH_PASSWORD=activecypher
    volumes:
      - memgraph_data:/var/lib/memgraph

  memgraphlab:
    image: memgraph/lab:latest
    ports:
      - "3000:3000" # Web UI
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
volumes:
  neo4j_data:
  memgraph_data:
