services:
  neo4j:
    image: neo4j:latest
    ports:
      - "${NEO4J_PORT:-17687}:7687" # Bolt
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-activecypher}
    volumes:
      - neo4j_data:/data

  memgraph:
    image: memgraph/memgraph-mage:latest
    ports:
      - "${MEMGRAPH_PORT:-17688}:7687" # Bolt protocol
      - "17444:7444"
    environment:
      - MEMGRAPH_USER=${MEMGRAPH_USER:-memgraph}
      - MEMGRAPH_PASSWORD=${MEMGRAPH_PASSWORD:-activecypher}
    volumes:
      - memgraph_data:/var/lib/memgraph

  memgraphlab:
    image: memgraph/lab:latest
    ports:
      - "13000:3000" # Web UI
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
volumes:
  neo4j_data:
  memgraph_data:
